// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MeshØ Compute Escrow Contract
 * @dev Coordinates trustless compute job scheduling, escrowing funds, and verifying
 * cryptographic compute receipts generated by worker nodes.
 */
contract MeshEscrow {
    
    struct Job {
        address client;
        uint256 escrowedAmount;
        bool isCompleted;
    }

    // Mapping from Task ID to Job escrow data
    mapping(uint64 => Job) public jobs;
    
    // Mapping of authorized worker addresses (for reputation/permissioned pools)
    mapping(address => bool) public authorizedWorkers;

    // Events
    event JobEscrowed(uint64 indexed taskId, address indexed client, uint256 amount);
    event PayoutClaimed(uint64 indexed taskId, address indexed worker, uint256 payoutAmount, uint256 refundAmount);
    event WorkerAuthorized(address indexed worker, bool status);

    address public owner;

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can call this");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    function setWorkerAuthorization(address worker, bool status) external onlyOwner {
        authorizedWorkers[worker] = status;
        emit WorkerAuthorized(worker, status);
    }

    /**
     * @dev Clients deposit funds into escrow for a specific compute task.
     * @param taskId Unique identifier for the WASM task.
     */
    function deposit(uint64 taskId) external payable {
        require(msg.value > 0, "Escrow deposit must be greater than zero");
        require(jobs[taskId].client == address(0), "Job already exists");

        jobs[taskId] = Job({
            client: msg.sender,
            escrowedAmount: msg.value,
            isCompleted: false
        });

        emit JobEscrowed(taskId, msg.sender, msg.value);
    }

    /**
     * @dev Workers submit signed receipts to claim payouts.
     * @param taskId Unique task identifier matching the deposit.
     * @param executionTimeMs Execution duration in milliseconds.
     * @param pricePerMs Charge rate per millisecond of compute.
     * @param totalPrice Cumulative cost calculated by the worker.
     * @param signature Cryptographic signature of the receipt parameters by the worker.
     */
    function claimPayout(
        uint64 taskId,
        uint256 executionTimeMs,
        uint256 pricePerMs,
        uint256 totalPrice,
        bytes calldata signature
    ) external {
        Job storage job = jobs[taskId];
        require(job.client != address(0), "Job does not exist");
        require(!job.isCompleted, "Payout already claimed");
        
        // Calculate expected cost: executionTimeMs * pricePerMs
        uint256 expectedCost = executionTimeMs * pricePerMs;
        require(totalPrice == expectedCost, "Calculated cost mismatch");
        require(job.escrowedAmount >= totalPrice, "Insufficient escrowed funds");

        // Verify the signature
        bytes32 messageHash = keccak256(abi.encodePacked(taskId, executionTimeMs, pricePerMs, totalPrice));
        bytes32 ethSignedMessageHash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash));
        
        address signer = recoverSigner(ethSignedMessageHash, signature);
        
        // Ensure the signer is the worker executing the transaction
        require(signer == msg.sender, "Signature does not match transaction sender");
        
        // Verify worker authorization if strict pool permissions are enabled
        if (owner != address(0)) {
            require(authorizedWorkers[signer], "Worker is not authorized");
        }

        job.isCompleted = true;
        uint256 payout = totalPrice;
        uint256 refund = job.escrowedAmount - payout;

        // Reset escrow amount before transfer to prevent re-entrancy
        job.escrowedAmount = 0;

        // Payout to worker
        (bool payoutSuccess, ) = payable(signer).call{value: payout}("");
        require(payoutSuccess, "Payout transfer failed");

        // Refund excess back to client
        if (refund > 0) {
            (bool refundSuccess, ) = payable(job.client).call{value: refund}("");
            require(refundSuccess, "Refund transfer failed");
        }

        emit PayoutClaimed(taskId, signer, payout, refund);
    }

    function recoverSigner(bytes32 _ethSignedMessageHash, bytes memory _signature) internal pure returns (address) {
        (bytes32 r, bytes32 s, uint8 v) = splitSignature(_signature);
        return ecrecover(_ethSignedMessageHash, v, r, s);
    }

    function splitSignature(bytes memory sig) internal pure returns (bytes32 r, bytes32 s, uint8 v) {
        require(sig.length == 65, "invalid signature length");

        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }
    }
}
